from .BoatOverfilledTest import BoatOverfilledTest
from .BoatShoreTests import BoatShoreTests
from .test_moveValidity import testMoveValidity
from .BoatSpacesTests import BoatSpacesTests
from .LocationTest import LocationTest
from .EndGameTest import EndGameTest
from .NewGameTest import NewGameTest
from .SetNewGameTest import SetNewGameTest
from .GUITest import GUITest
from .RulesTest import RulesTest